name: Spellcheck

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Spellchecker
      run: sudo apt-get install -y aspell aspell-en

    - name: Run Spellcheck
      run: |
        find . -type f -name '*.md' -exec aspell --lang=en --mode=markdown check {} \;